export const projects = [
  {
    id: 1,
    title: "URL Shortner",
    description: "A full stack project where you can short your url quickly.",
    image: '/projects-images/img.jpg',
    liveURL: "https://calcora.us/",
    githubURL: "https://github.com/",
    stack: ["MongoDb", "React", "Express", "Node"],
  },
  {
    id: 2,
    title: "URL Shortner",
    description: "A full stack project where you can short your url quickly.",
    image: '/img.jpg',
    liveURL: "https://calcora.us/",
    githubURL: "https://github.com/",
    stack: ["MongoDb", "React", "Express", "Node"],
  },
  {
    id: 3,
    title: "URL Shortner",
    description: "A full stack project where you can short your url quickly.",
    image: '/img.jpg',
    liveURL: "https://calcora.us/",
    githubURL: "https://github.com/",
    stack: ["MongoDb", "React", "Express", "Node"],
  },
  {
    id: 4,
    title: "URL Shortner",
    description: "A full stack project where you can short your url quickly.",
    image: '/img.jpg',
    liveURL: "https://calcora.us/",
    githubURL: "https://github.com/",
    stack: ["MongoDb", "React", "Express", "Node"],
  },
];
